// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using turnotucapp.Data;

namespace turnotucapp.Migrations.AppTurnoTucDb
{
    [DbContext(typeof(AppTurnoTucDbContext))]
    [Migration("20191123014914_NewMigration")]
    partial class NewMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("turnotucapp.Models.BocaDeAtencion", b =>
                {
                    b.Property<int>("BocaDeAtencionID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("DescripcionAtencion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("NumeroDeAtencion")
                        .HasColumnType("int");

                    b.Property<int?>("SucursalID")
                        .HasColumnType("int");

                    b.Property<string>("TipoAtencion")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("BocaDeAtencionID");

                    b.HasIndex("SucursalID");

                    b.ToTable("Atencions");
                });

            modelBuilder.Entity("turnotucapp.Models.ObraSocial", b =>
                {
                    b.Property<int>("ObraSocialID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<double>("Cuit")
                        .HasColumnType("float");

                    b.Property<string>("Direccion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RazonSocial")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ObraSocialID");

                    b.ToTable("Obras");
                });

            modelBuilder.Entity("turnotucapp.Models.Paciente", b =>
                {
                    b.Property<int>("PacienteID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.HasKey("PacienteID");

                    b.ToTable("Pacientes");
                });

            modelBuilder.Entity("turnotucapp.Models.Sucursal", b =>
                {
                    b.Property<int>("SucursalID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("NombreSucursal")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("SucursalID");

                    b.ToTable("Sucursals");
                });

            modelBuilder.Entity("turnotucapp.Models.Turno", b =>
                {
                    b.Property<int>("TurnoID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Estado")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("datetime2");

                    b.Property<int>("Numero")
                        .HasColumnType("int");

                    b.Property<int?>("PacienteID")
                        .HasColumnType("int");

                    b.HasKey("TurnoID");

                    b.HasIndex("PacienteID");

                    b.ToTable("Turnos");
                });

            modelBuilder.Entity("turnotucapp.Models.BocaDeAtencion", b =>
                {
                    b.HasOne("turnotucapp.Models.Sucursal", null)
                        .WithMany("Atencions")
                        .HasForeignKey("SucursalID");
                });

            modelBuilder.Entity("turnotucapp.Models.Turno", b =>
                {
                    b.HasOne("turnotucapp.Models.Paciente", "Paciente")
                        .WithMany()
                        .HasForeignKey("PacienteID");
                });
#pragma warning restore 612, 618
        }
    }
}
